FROM microsoft/dotnet:2.1-runtime-stretch-slim

WORKDIR /app
COPY ./bin/Release/netcoreapp2.1/publish .

RUN useradd -ms /bin/bash moduleuser
USER moduleuser

ENTRYPOINT ["dotnet", "DeviceDiagnostics.dll"]